// GENERATED by `pnpm gen:api` from api/lifecycle.json — do not edit by hand.
// Source of truth: api/src/wild_life/lifecycle.py

/** The shared "state of work" every entity status projects onto. */
export type LifecyclePhase = "backlog" | "active" | "blocked" | "done" | "cancelled"

/** entity type → status → phase. Total over every status `Literal` the API
 *  defines; `api/tests/test_lifecycle.py` fails if one goes unclassified. */
export const LIFECYCLE = {
  "allergy": {
    "active": "active",
    "resolved": "done",
    "suspected": "active",
  },
  "area": {
    "active": "active",
    "archived": "done",
    "inactive": "blocked",
  },
  "commitment": {
    "broken": "cancelled",
    "cancelled": "cancelled",
    "fulfilled": "done",
    "in_progress": "active",
    "open": "active",
    "waiting": "blocked",
  },
  "delegation": {
    "accepted": "active",
    "accepted_as_complete": "done",
    "blocked": "blocked",
    "cancelled": "cancelled",
    "declined": "cancelled",
    "delivered": "active",
    "draft": "backlog",
    "in_progress": "active",
    "reassigned": "cancelled",
    "requested": "active",
    "revision_requested": "active",
    "waiting_for_update": "blocked",
  },
  "insurance_plan": {
    "active": "active",
    "inactive": "done",
  },
  "organization": {
    "active": "active",
    "archived": "done",
    "inactive": "blocked",
  },
  "outcome": {
    "achieved": "done",
    "active": "active",
    "dropped": "cancelled",
    "paused": "blocked",
  },
  "program": {
    "active": "active",
    "cancelled": "cancelled",
    "monitoring": "active",
    "paused": "blocked",
    "proposed": "backlog",
    "resolved": "done",
  },
  "project": {
    "active": "active",
    "archived": "done",
    "cancelled": "cancelled",
    "completed": "done",
    "paused": "blocked",
    "proposed": "backlog",
    "waiting": "blocked",
  },
  "request": {
    "cancelled": "cancelled",
    "open": "active",
    "resolved": "done",
  },
  "routine": {
    "active": "active",
    "archived": "done",
    "paused": "blocked",
  },
  "task": {
    "cancelled": "cancelled",
    "completed": "done",
    "delegated": "active",
    "delivered": "active",
    "in_progress": "active",
    "inbox": "backlog",
    "planned": "backlog",
    "waiting": "blocked",
  },
} as const satisfies Record<string, Record<string, LifecyclePhase>>
