"""life management model

Revision ID: 0aca9263467f
Revises:
Create Date: 2026-07-15 07:11:34.050673
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0aca9263467f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("note_type", sa.Text(), server_default="note", nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("mood", sa.Text(), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_notes_entity_id"),
        "notes",
        ["entity_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_notes_entry_date"),
        "notes",
        ["entry_date"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "people",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=True),
        sa.Column("organization", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column(
            "emails", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "phones", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("preferred_contact", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_table(
        "resources",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_table(
        "reviews",
        sa.Column("review_type", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column(
            "entities_reviewed",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("decisions", sa.Text(), nullable=True),
        sa.Column("risks", sa.Text(), nullable=True),
        sa.Column("follow_up_actions", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_tags_name"),
        schema="personal_api",
    )
    op.create_table(
        "areas",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("desired_standard", sa.Text(), nullable=True),
        sa.Column("review_frequency", sa.Text(), nullable=True),
        sa.Column("accountable_owner_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accountable_owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_areas_accountable_owner_id"),
        "areas",
        ["accountable_owner_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "commitments",
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("beneficiary_id", sa.UUID(), nullable=True),
        sa.Column("responsible_id", sa.UUID(), nullable=True),
        sa.Column("date_made", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("acceptance_status", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_table(
        "decisions",
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("options_considered", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("assumptions", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("decided_on", sa.Date(), nullable=True),
        sa.Column("review_date", sa.Date(), nullable=True),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_table(
        "delegations",
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("delegator_id", sa.UUID(), nullable=True),
        sa.Column("responsible_id", sa.UUID(), nullable=True),
        sa.Column("accountable_owner_id", sa.UUID(), nullable=True),
        sa.Column("date_delegated", sa.Date(), nullable=True),
        sa.Column("requested_outcome", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("priority", sa.Text(), server_default="medium", nullable=False),
        sa.Column("expected_completion_date", sa.Date(), nullable=True),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column(
            "acceptance_required", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("latest_update", sa.Text(), nullable=True),
        sa.Column("last_contact_date", sa.Date(), nullable=True),
        sa.Column("delivered_date", sa.Date(), nullable=True),
        sa.Column("accepted_date", sa.Date(), nullable=True),
        sa.Column("completion_evidence", sa.Text(), nullable=True),
        sa.Column("escalation_level", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accountable_owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["delegator_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_delegations_follow_up_date"),
        "delegations",
        ["follow_up_date"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_delegations_responsible_id"),
        "delegations",
        ["responsible_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "entity_tags",
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["personal_api.tags.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tag_id", "entity_type", "entity_id"),
        schema="personal_api",
    )
    op.create_table(
        "interactions",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["personal_api.people.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_interactions_person_id"),
        "interactions",
        ["person_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "waiting_items",
        sa.Column("expected_result", sa.Text(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=True),
        sa.Column("from_org", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("date_requested", sa.Date(), nullable=True),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("last_communication", sa.Text(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_waiting_items_follow_up_date"),
        "waiting_items",
        ["follow_up_date"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "programs",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("intended_outcome", sa.Text(), nullable=True),
        sa.Column("success_criteria", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="proposed", nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("accountable_owner_id", sa.UUID(), nullable=True),
        sa.Column("responsible_lead_id", sa.UUID(), nullable=True),
        sa.Column("review_frequency", sa.Text(), nullable=True),
        sa.Column("reporting_cadence", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accountable_owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["responsible_lead_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_programs_accountable_owner_id"),
        "programs",
        ["accountable_owner_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_programs_area_id"),
        "programs",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_programs_responsible_lead_id"),
        "programs",
        ["responsible_lead_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "metrics",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("target_value", sa.Float(), nullable=True),
        sa.Column("target_min", sa.Float(), nullable=True),
        sa.Column("target_max", sa.Float(), nullable=True),
        sa.Column("measurement_frequency", sa.Text(), nullable=True),
        sa.Column("data_source", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["personal_api.programs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_metrics_area_id"),
        "metrics",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_metrics_program_id"),
        "metrics",
        ["program_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("intended_outcome", sa.Text(), nullable=True),
        sa.Column("completion_criteria", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="proposed", nullable=False),
        sa.Column("priority", sa.Text(), server_default="medium", nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("accountable_owner_id", sa.UUID(), nullable=True),
        sa.Column("responsible_lead_id", sa.UUID(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=True),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accountable_owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["personal_api.programs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["responsible_lead_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_projects_accountable_owner_id"),
        "projects",
        ["accountable_owner_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_projects_area_id"),
        "projects",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_projects_program_id"),
        "projects",
        ["program_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_projects_responsible_lead_id"),
        "projects",
        ["responsible_lead_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "routines",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("frequency", sa.Text(), nullable=True),
        sa.Column(
            "preferred_days",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("preferred_time", sa.Text(), nullable=True),
        sa.Column("tracking_method", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("responsible_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["personal_api.programs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_routines_area_id"),
        "routines",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_routines_program_id"),
        "routines",
        ["program_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "events",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_day", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "attendees",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["personal_api.programs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["personal_api.projects.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_events_area_id"),
        "events",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "goals",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("metric_id", sa.UUID(), nullable=True),
        sa.Column("target_state", sa.Text(), nullable=True),
        sa.Column("target_value", sa.Float(), nullable=True),
        sa.Column("baseline", sa.Float(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("measurement_method", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"], ["personal_api.metrics.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["personal_api.programs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_goals_area_id"),
        "goals",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_goals_program_id"),
        "goals",
        ["program_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "metric_entries",
        sa.Column("metric_id", sa.UUID(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"], ["personal_api.metrics.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_metric_entries_entry_date"),
        "metric_entries",
        ["entry_date"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_metric_entries_metric_id"),
        "metric_entries",
        ["metric_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "project_contributors",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["personal_api.people.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["personal_api.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "person_id"),
        schema="personal_api",
    )
    op.create_table(
        "routine_instances",
        sa.Column("routine_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["routine_id"], ["personal_api.routines.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_routine_instances_routine_id"),
        "routine_instances",
        ["routine_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_routine_instances_scheduled_date"),
        "routine_instances",
        ["scheduled_date"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "tasks",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="inbox", nullable=False),
        sa.Column("area_id", sa.UUID(), nullable=True),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("priority", sa.Text(), server_default="medium", nullable=False),
        sa.Column("accountable_owner_id", sa.UUID(), nullable=True),
        sa.Column("responsible_id", sa.UUID(), nullable=True),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("recurrence", sa.Text(), nullable=True),
        sa.Column("blocked_by_task_id", sa.UUID(), nullable=True),
        sa.Column("waiting_on", sa.Text(), nullable=True),
        sa.Column(
            "acceptance_required", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accountable_owner_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["area_id"], ["personal_api.areas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["blocked_by_task_id"], ["personal_api.tasks.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["personal_api.programs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["personal_api.projects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["responsible_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_tasks_area_id"),
        "tasks",
        ["area_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_tasks_assignee_id"),
        "tasks",
        ["assignee_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_tasks_program_id"),
        "tasks",
        ["program_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_tasks_project_id"),
        "tasks",
        ["project_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_table(
        "goal_projects",
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"], ["personal_api.goals.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["personal_api.projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("goal_id", "project_id"),
        schema="personal_api",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goal_projects", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_tasks_project_id"),
        table_name="tasks",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_tasks_program_id"),
        table_name="tasks",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_tasks_assignee_id"),
        table_name="tasks",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_tasks_area_id"), table_name="tasks", schema="personal_api"
    )
    op.drop_table("tasks", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_routine_instances_scheduled_date"),
        table_name="routine_instances",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_routine_instances_routine_id"),
        table_name="routine_instances",
        schema="personal_api",
    )
    op.drop_table("routine_instances", schema="personal_api")
    op.drop_table("project_contributors", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_metric_entries_metric_id"),
        table_name="metric_entries",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_metric_entries_entry_date"),
        table_name="metric_entries",
        schema="personal_api",
    )
    op.drop_table("metric_entries", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_goals_program_id"),
        table_name="goals",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_goals_area_id"), table_name="goals", schema="personal_api"
    )
    op.drop_table("goals", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_events_area_id"),
        table_name="events",
        schema="personal_api",
    )
    op.drop_table("events", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_routines_program_id"),
        table_name="routines",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_routines_area_id"),
        table_name="routines",
        schema="personal_api",
    )
    op.drop_table("routines", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_projects_responsible_lead_id"),
        table_name="projects",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_projects_program_id"),
        table_name="projects",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_projects_area_id"),
        table_name="projects",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_projects_accountable_owner_id"),
        table_name="projects",
        schema="personal_api",
    )
    op.drop_table("projects", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_metrics_program_id"),
        table_name="metrics",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_metrics_area_id"),
        table_name="metrics",
        schema="personal_api",
    )
    op.drop_table("metrics", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_programs_responsible_lead_id"),
        table_name="programs",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_programs_area_id"),
        table_name="programs",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_programs_accountable_owner_id"),
        table_name="programs",
        schema="personal_api",
    )
    op.drop_table("programs", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_waiting_items_follow_up_date"),
        table_name="waiting_items",
        schema="personal_api",
    )
    op.drop_table("waiting_items", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_interactions_person_id"),
        table_name="interactions",
        schema="personal_api",
    )
    op.drop_table("interactions", schema="personal_api")
    op.drop_table("entity_tags", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_delegations_responsible_id"),
        table_name="delegations",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_delegations_follow_up_date"),
        table_name="delegations",
        schema="personal_api",
    )
    op.drop_table("delegations", schema="personal_api")
    op.drop_table("decisions", schema="personal_api")
    op.drop_table("commitments", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_areas_accountable_owner_id"),
        table_name="areas",
        schema="personal_api",
    )
    op.drop_table("areas", schema="personal_api")
    op.drop_table("tags", schema="personal_api")
    op.drop_table("reviews", schema="personal_api")
    op.drop_table("resources", schema="personal_api")
    op.drop_table("people", schema="personal_api")
    op.drop_index(
        op.f("ix_personal_api_notes_entry_date"),
        table_name="notes",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_notes_entity_id"),
        table_name="notes",
        schema="personal_api",
    )
    op.drop_table("notes", schema="personal_api")
    # ### end Alembic commands ###
