"""expand person fields

Revision ID: 689a01c6381a
Revises: 0aca9263467f
Create Date: 2026-07-15 08:11:59.330953
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '689a01c6381a'
down_revision: str | None = '0aca9263467f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('nickname', sa.Text(), nullable=True), schema='wild_life')
    op.add_column('people', sa.Column('job_title', sa.Text(), nullable=True), schema='wild_life')
    op.add_column('people', sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='wild_life')
    op.add_column('people', sa.Column('websites', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False), schema='wild_life')
    op.add_column('people', sa.Column('birthday', sa.Date(), nullable=True), schema='wild_life')
    op.add_column('people', sa.Column('important_dates', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='wild_life')
    op.add_column('people', sa.Column('photo_url', sa.Text(), nullable=True), schema='wild_life')
    # phones/emails change from text[] to JSONB (typed contact methods). The
    # table is empty at this migration, so drop + re-add is cleaner than a cast.
    op.drop_column('people', 'phones', schema='wild_life')
    op.drop_column('people', 'emails', schema='wild_life')
    op.add_column('people', sa.Column('phones', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='wild_life')
    op.add_column('people', sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='wild_life')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'emails', schema='wild_life')
    op.drop_column('people', 'phones', schema='wild_life')
    op.add_column('people', sa.Column('emails', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False), schema='wild_life')
    op.add_column('people', sa.Column('phones', postgresql.ARRAY(sa.TEXT()), server_default='{}', nullable=False), schema='wild_life')
    op.drop_column('people', 'photo_url', schema='wild_life')
    op.drop_column('people', 'important_dates', schema='wild_life')
    op.drop_column('people', 'birthday', schema='wild_life')
    op.drop_column('people', 'websites', schema='wild_life')
    op.drop_column('people', 'addresses', schema='wild_life')
    op.drop_column('people', 'job_title', schema='wild_life')
    op.drop_column('people', 'nickname', schema='wild_life')
    # ### end Alembic commands ###
