"""add requests, retire waiting_items

Revision ID: 745e9a805428
Revises: 65c47f412a47
Create Date: 2026-07-18 16:05:58.422942
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "745e9a805428"
down_revision: str | None = "65c47f412a47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("requester_id", sa.UUID(), nullable=True),
        sa.Column("addressee_id", sa.UUID(), nullable=True),
        sa.Column("external_label", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), server_default="question", nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("needed_by", sa.Date(), nullable=True),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_communication", sa.Text(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["addressee_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_requests_addressee_id"),
        "requests",
        ["addressee_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_requests_follow_up_date"),
        "requests",
        ["follow_up_date"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_requests_requester_id"),
        "requests",
        ["requester_id"],
        unique=False,
        schema="personal_api",
    )

    # Migrate any existing waiting items into requests (kept id so soft-links stay
    # valid): person_owed -> addressee, from_org -> external_label, kind=deliverable.
    op.execute(
        sa.text("""
        insert into personal_api.requests
            (id, requester_id, addressee_id, external_label, kind, subject,
             entity_type, entity_id, needed_by, follow_up_date, status,
             last_communication, next_action, notes, created_at, updated_at)
        select id, null, person_id, from_org, 'deliverable', expected_result,
               entity_type, entity_id, expected_date, follow_up_date,
               case when status = 'received' then 'resolved'
                    when status = 'cancelled' then 'cancelled'
                    else 'open' end,
               last_communication, next_action, notes, created_at, updated_at
        from personal_api.waiting_items
    """)
    )
    # Repoint stored soft-links from the old type string to the new one.
    for tbl, col in (
        ("notes", "entity_type"),
        ("note_mentions", "target_type"),
        ("entity_tags", "entity_type"),
        ("commitments", "entity_type"),
        ("delegations", "entity_type"),
        ("resources", "entity_type"),
        ("decisions", "entity_type"),
    ):
        op.execute(
            sa.text(
                f"update personal_api.{tbl} set {col} = 'request' "
                f"where {col} = 'waiting_item'"
            )
        )

    op.drop_index(
        op.f("ix_personal_api_waiting_items_follow_up_date"),
        table_name="waiting_items",
        schema="personal_api",
    )
    op.drop_table("waiting_items", schema="personal_api")


def downgrade() -> None:
    op.create_table(
        "waiting_items",
        sa.Column("expected_result", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("person_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("from_org", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("entity_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("date_requested", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("expected_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("follow_up_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'open'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("last_communication", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("next_action", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["personal_api.people.id"],
            name=op.f("waiting_items_person_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("waiting_items_pkey")),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_waiting_items_follow_up_date"),
        "waiting_items",
        ["follow_up_date"],
        unique=False,
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_requests_requester_id"),
        table_name="requests",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_requests_follow_up_date"),
        table_name="requests",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_requests_addressee_id"),
        table_name="requests",
        schema="personal_api",
    )
    op.drop_table("requests", schema="personal_api")
    # ### end Alembic commands ###
