"""add api_tokens

Revision ID: 87d25560be8f
Revises: e7a8b9c0d1f2
Create Date: 2026-07-18 15:43:07.801817
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "87d25560be8f"
down_revision: str | None = "e7a8b9c0d1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), server_default="worker", nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["personal_api.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_api_tokens_person_id"),
        "api_tokens",
        ["person_id"],
        unique=False,
        schema="personal_api",
    )
    op.create_index(
        op.f("ix_personal_api_api_tokens_token_hash"),
        "api_tokens",
        ["token_hash"],
        unique=True,
        schema="personal_api",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_personal_api_api_tokens_token_hash"),
        table_name="api_tokens",
        schema="personal_api",
    )
    op.drop_index(
        op.f("ix_personal_api_api_tokens_person_id"),
        table_name="api_tokens",
        schema="personal_api",
    )
    op.drop_table("api_tokens", schema="personal_api")
