"""note images

Revision ID: 8c9e89f4c05b
Revises: f1a2b3c4d5e6
Create Date: 2026-07-15 12:29:09.877730
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8c9e89f4c05b'
down_revision: str | None = 'f1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_images',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['wild_life.notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='wild_life'
    )
    op.create_index('ix_note_images_note', 'note_images', ['note_id'], unique=False, schema='wild_life')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_images_note', table_name='note_images', schema='wild_life')
    op.drop_table('note_images', schema='wild_life')
    # ### end Alembic commands ###
