"""dose-event log: amount_taken + ad_hoc on routine_instances

Turns routine_instances into a true dose-event log while keeping the scheduled
check-off idempotent. Adds ``amount_taken`` (actual per-dose quantity) and an
``ad_hoc`` discriminator: ``ad_hoc=false`` rows are scheduled check-offs (one per
routine/day/slot); ``ad_hoc=true`` rows are extra/PRN/backdated doses (unbounded).

The old full unique index ``uq_routine_instance`` is replaced with a **partial**
unique index that applies only to scheduled rows (``WHERE ad_hoc = false``), so
several ad-hoc doses can share a (routine, day, slot). Hand-written (not
autogenerated) because autogenerate does not emit partial-index predicates.

Revision ID: c3d4e5f6a7b8
Revises: b29623e206f2
Create Date: 2026-07-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c3d4e5f6a7b8"
down_revision: str | None = "b29623e206f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "routine_instances",
        sa.Column("amount_taken", sa.Numeric(), nullable=True),
        schema="wild_life",
    )
    # Existing rows backfill to false (scheduled check-offs); safe because the old
    # full unique index guaranteed they satisfy the new partial unique index.
    op.add_column(
        "routine_instances",
        sa.Column(
            "ad_hoc", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        schema="wild_life",
    )
    op.drop_index(
        "uq_routine_instance", table_name="routine_instances", schema="wild_life"
    )
    op.create_index(
        "uq_routine_instance_scheduled",
        "routine_instances",
        ["routine_id", "scheduled_date", "slot"],
        unique=True,
        postgresql_where=sa.text("ad_hoc = false"),
        schema="wild_life",
    )


def downgrade() -> None:
    op.drop_index(
        "uq_routine_instance_scheduled",
        table_name="routine_instances",
        schema="wild_life",
    )
    # Ad-hoc doses have no place in the pre-feature model and could violate the full
    # unique index (multiple PRN doses per day/slot) — drop them before recreating it.
    op.execute("DELETE FROM wild_life.routine_instances WHERE ad_hoc = true")
    op.create_index(
        "uq_routine_instance",
        "routine_instances",
        ["routine_id", "scheduled_date", "slot"],
        unique=True,
        schema="wild_life",
    )
    op.drop_column("routine_instances", "ad_hoc", schema="wild_life")
    op.drop_column("routine_instances", "amount_taken", schema="wild_life")
