"""link conditions and protocols to area/program

Revision ID: cc12676f0455
Revises: ee911f4d1219
Create Date: 2026-07-15 09:33:17.205060
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cc12676f0455'
down_revision: str | None = 'ee911f4d1219'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('area_id', sa.UUID(), nullable=True), schema='wild_life')
    op.add_column('conditions', sa.Column('program_id', sa.UUID(), nullable=True), schema='wild_life')
    op.create_index(op.f('ix_wild_life_conditions_area_id'), 'conditions', ['area_id'], unique=False, schema='wild_life')
    op.create_index(op.f('ix_wild_life_conditions_program_id'), 'conditions', ['program_id'], unique=False, schema='wild_life')
    op.create_foreign_key(None, 'conditions', 'programs', ['program_id'], ['id'], source_schema='wild_life', referent_schema='wild_life', ondelete='SET NULL')
    op.create_foreign_key(None, 'conditions', 'areas', ['area_id'], ['id'], source_schema='wild_life', referent_schema='wild_life', ondelete='SET NULL')
    op.add_column('protocols', sa.Column('area_id', sa.UUID(), nullable=True), schema='wild_life')
    op.add_column('protocols', sa.Column('program_id', sa.UUID(), nullable=True), schema='wild_life')
    op.create_index(op.f('ix_wild_life_protocols_area_id'), 'protocols', ['area_id'], unique=False, schema='wild_life')
    op.create_index(op.f('ix_wild_life_protocols_program_id'), 'protocols', ['program_id'], unique=False, schema='wild_life')
    op.create_foreign_key(None, 'protocols', 'programs', ['program_id'], ['id'], source_schema='wild_life', referent_schema='wild_life', ondelete='SET NULL')
    op.create_foreign_key(None, 'protocols', 'areas', ['area_id'], ['id'], source_schema='wild_life', referent_schema='wild_life', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'protocols', schema='wild_life', type_='foreignkey')
    op.drop_constraint(None, 'protocols', schema='wild_life', type_='foreignkey')
    op.drop_index(op.f('ix_wild_life_protocols_program_id'), table_name='protocols', schema='wild_life')
    op.drop_index(op.f('ix_wild_life_protocols_area_id'), table_name='protocols', schema='wild_life')
    op.drop_column('protocols', 'program_id', schema='wild_life')
    op.drop_column('protocols', 'area_id', schema='wild_life')
    op.drop_constraint(None, 'conditions', schema='wild_life', type_='foreignkey')
    op.drop_constraint(None, 'conditions', schema='wild_life', type_='foreignkey')
    op.drop_index(op.f('ix_wild_life_conditions_program_id'), table_name='conditions', schema='wild_life')
    op.drop_index(op.f('ix_wild_life_conditions_area_id'), table_name='conditions', schema='wild_life')
    op.drop_column('conditions', 'program_id', schema='wild_life')
    op.drop_column('conditions', 'area_id', schema='wild_life')
    # ### end Alembic commands ###
