"""add health domain

Revision ID: ee911f4d1219
Revises: d3f5a7b9c2e4
Create Date: 2026-07-15 09:13:52.467260
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "ee911f4d1219"
down_revision: str | None = "d3f5a7b9c2e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergies",
        sa.Column("substance", sa.Text(), nullable=False),
        sa.Column("allergy_type", sa.Text(), nullable=True),
        sa.Column("reaction", sa.Text(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("noted_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_table(
        "conditions",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("onset_date", sa.Date(), nullable=True),
        sa.Column("resolved_date", sa.Date(), nullable=True),
        sa.Column("diagnosed_by_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["diagnosed_by_id"], ["wild_life.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_table(
        "insurance_plans",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("plan_type", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("network", sa.Text(), nullable=True),
        sa.Column("member_id", sa.Text(), nullable=True),
        sa.Column("group_number", sa.Text(), nullable=True),
        sa.Column("rx_bin", sa.Text(), nullable=True),
        sa.Column("rx_pcn", sa.Text(), nullable=True),
        sa.Column("rx_group", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["wild_life.organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_insurance_plans_organization_id"),
        "insurance_plans",
        ["organization_id"],
        unique=False,
        schema="wild_life",
    )
    op.create_table(
        "health_events",
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column(
            "event_type", sa.Text(), server_default="appointment", nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("condition_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("findings", sa.Text(), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("follow_up", sa.Text(), nullable=True),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["condition_id"], ["wild_life.conditions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["wild_life.organizations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["wild_life.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_health_events_condition_id"),
        "health_events",
        ["condition_id"],
        unique=False,
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_health_events_occurred_on"),
        "health_events",
        ["occurred_on"],
        unique=False,
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_health_events_organization_id"),
        "health_events",
        ["organization_id"],
        unique=False,
        schema="wild_life",
    )
    op.create_table(
        "medications",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("generic_name", sa.Text(), nullable=True),
        sa.Column("med_type", sa.Text(), server_default="supplement", nullable=False),
        sa.Column("form", sa.Text(), nullable=True),
        sa.Column("strength", sa.Text(), nullable=True),
        sa.Column("dose", sa.Text(), nullable=True),
        sa.Column(
            "schedule",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("condition_id", sa.UUID(), nullable=True),
        sa.Column("prescriber_id", sa.UUID(), nullable=True),
        sa.Column("pharmacy_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["condition_id"], ["wild_life.conditions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["pharmacy_id"], ["wild_life.organizations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["prescriber_id"], ["wild_life.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_medications_condition_id"),
        "medications",
        ["condition_id"],
        unique=False,
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_medications_pharmacy_id"),
        "medications",
        ["pharmacy_id"],
        unique=False,
        schema="wild_life",
    )
    op.create_table(
        "protocols",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("intended_outcome", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="planned", nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("duration", sa.Text(), nullable=True),
        sa.Column("condition_id", sa.UUID(), nullable=True),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["condition_id"], ["wild_life.conditions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["wild_life.people.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_protocols_condition_id"),
        "protocols",
        ["condition_id"],
        unique=False,
        schema="wild_life",
    )
    op.create_table(
        "protocol_items",
        sa.Column("protocol_id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=True),
        sa.Column("substance", sa.Text(), nullable=True),
        sa.Column("amount", sa.Text(), nullable=True),
        sa.Column(
            "timing", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("frequency", sa.Text(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"], ["wild_life.medications.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["protocol_id"], ["wild_life.protocols.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wild_life",
    )
    op.create_index(
        op.f("ix_wild_life_protocol_items_protocol_id"),
        "protocol_items",
        ["protocol_id"],
        unique=False,
        schema="wild_life",
    )
    op.add_column(
        "people", sa.Column("specialty", sa.Text(), nullable=True), schema="wild_life"
    )
    op.add_column(
        "people", sa.Column("patient_id", sa.Text(), nullable=True), schema="wild_life"
    )
    op.add_column(
        "people", sa.Column("portal_url", sa.Text(), nullable=True), schema="wild_life"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("people", "portal_url", schema="wild_life")
    op.drop_column("people", "patient_id", schema="wild_life")
    op.drop_column("people", "specialty", schema="wild_life")
    op.drop_index(
        op.f("ix_wild_life_protocol_items_protocol_id"),
        table_name="protocol_items",
        schema="wild_life",
    )
    op.drop_table("protocol_items", schema="wild_life")
    op.drop_index(
        op.f("ix_wild_life_protocols_condition_id"),
        table_name="protocols",
        schema="wild_life",
    )
    op.drop_table("protocols", schema="wild_life")
    op.drop_index(
        op.f("ix_wild_life_medications_pharmacy_id"),
        table_name="medications",
        schema="wild_life",
    )
    op.drop_index(
        op.f("ix_wild_life_medications_condition_id"),
        table_name="medications",
        schema="wild_life",
    )
    op.drop_table("medications", schema="wild_life")
    op.drop_index(
        op.f("ix_wild_life_health_events_organization_id"),
        table_name="health_events",
        schema="wild_life",
    )
    op.drop_index(
        op.f("ix_wild_life_health_events_occurred_on"),
        table_name="health_events",
        schema="wild_life",
    )
    op.drop_index(
        op.f("ix_wild_life_health_events_condition_id"),
        table_name="health_events",
        schema="wild_life",
    )
    op.drop_table("health_events", schema="wild_life")
    op.drop_index(
        op.f("ix_wild_life_insurance_plans_organization_id"),
        table_name="insurance_plans",
        schema="wild_life",
    )
    op.drop_table("insurance_plans", schema="wild_life")
    op.drop_table("conditions", schema="wild_life")
    op.drop_table("allergies", schema="wild_life")
    # ### end Alembic commands ###
